name: .NET CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MS Build
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Packages
      run: nuget restore veracode.sln

    - name: Create Build Directory
      run: mkdir _build
    
    - name: Build Solution
      run: msbuild veracode.sln /p:OutputPath=bin /p:DeployOnBuild=true /p:PackageAsSingleFile=true /p:WebPublishMethod=FileSystem /p:PrecompileBeforePublish=true /p:EnableUpdateable=false /p:DebugSymbols=true /p:UseMerge=false /p:DeleteAppCodeCompiledFiles=True /p:DeleteExistingFiles=True /p:WDPMergeOption=CreateSeparateAssembly /p:UseFixedNames=true /p:PublishUrl="/_build"

    - name: Check dir
      run: dir -s
      
    - uses: papeloto/action-zip@v1
      with:
            files: bin/
            dest: veracode.zip
    - uses: actions/upload-artifact@master
      with:
        name: veracode_zip
        path: veracode.zip
        
  full-scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - uses: actions/download-artifact@master
        with:
          name: veracode_zip
          
      - name: Download Veracode Policy/Static Scan
        run: VERACODE_WRAPPER_VERSION=$(curl -sS "https://search.maven.org/solrsearch/select?q=g:%22com.veracode.vosp.api.wrappers%22&rows=20&wt=json" | jq -r '.response.docs[0].latestVersion') && curl -sS -o veracode-wrapper.jar "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VERACODE_WRAPPER_VERSION}/vosp-api-wrappers-java-${VERACODE_WRAPPER_VERSION}.jar"

      - name: Run Policy/Static Scan
        run: java -jar veracode-wrapper.jar -vid ${{secrets.VERACODE_API_ID}} -vkey ${{secrets.VERACODE_API_KEY}} -action uploadandscan -appname "NW.org GitHub Integration" -filepath "veracode.zip" -createprofile false -version "09_17_2021_v1" -createsandbox false -autoscan true   
        
      - name: Finish Scan
        run: echo "complete"
