name: .NET CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MS Build
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Packages
      run: nuget restore veracode.sln

    - name: Create Build Directory
      run: mkdir _build
    
    - name: Build Solution
      run: msbuild veracode.sln /p:OutputPath=bin /p:DeployOnBuild=true /p:PackageAsSingleFile=true /p:WebPublishMethod=FileSystem /p:PrecompileBeforePublish=true /p:EnableUpdateable=false /p:DebugSymbols=true /p:UseMerge=false /p:DeleteAppCodeCompiledFiles=True /p:DeleteExistingFiles=True /p:WDPMergeOption=CreateSeparateAssembly /p:UseFixedNames=true /p:PublishUrl="/_build"

    - name: Check dir
      run: dir
      
    - uses: actions/upload-artifact@master
      with:
        name: veracode_zip
        path: bin/_PublishedWebsites/veracode_Package/veracode.zip
        
  pipeline-scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
      - uses: actions/download-artifact@master
        with:
          name: veracode_zip

      - name: Check dir
        run: ls
      - name: Run Pipeline Scanner
        run: java -jar pipeline-scan.jar -v -jd {true} -jo {true} -f "veracode.zip" -vid "${{ secrets.VERACODE_API_ID }}" -vkey "${{ secrets.VERACODE_API_KEY }}"
    
